### ISSUE TITLE
More entries!

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/awesome-mobx#23]
https://gonehybrid.com/how-to-manage-state-in-ionic-apps-with-mobx-part-1/
https://github.com/ds300/redux-mobx-connect

**Comment by mweststrate** [comment]
https://school.shoutem.com/lectures/react-native-hackernews-app/?utm_medium=social&utm_source=twitter&utm_campaign=rn_school&utm_content=lecture_11

**Comment by hawkins** [comment]
As soon as I can determine my translation was acceptable and merge #24 , I'll get these in. Thanks for the resources as always 👍
