### ISSUE TITLE
Add streamflow

### ISSUE THREAD

**Issue by hawkins** [mobxjs/awesome-mobx#25]
I'm biased, but this is how I use MobX. May be breaking a few best practices I don't know of, but it's how I use it and it works wonderfully for me in electron and web apps! I've used this app's code countless times as a reference when explaining elements like state management in a slightly-more-than-todo-app level of complexity and basic data fetching etc.

https://github.com/hawkins/streamflow

**Comment by mweststrate** [comment]
Cool! just add it ;-)
