### ISSUE TITLE
征求中国读者的意见 

### ISSUE THREAD

**Issue by hawkins** [mobxjs/awesome-mobx#50]
大家好。 中文翻译有用吗？ 你甚至需要/使用它们吗？

由于即将推出的令人敬畏的mobx机器人在翻译过程中出现了一些问题，所以我打了一个残缺。 中国读者在翻译过程中是否找到了很多价值？ 我担心维护它们不再值得付出努力，因为如果我们放弃这些列表，并且允许读者根据需要使用Google翻译之类的内容进行翻译，那么维护此列表几乎可以免费。

这意味着丢弃它们（或者说，将它们归档到另一个回购库中）将使这个列表的管理变得更容易，并且使信息更容易保持最新。

我们的读者对此有何看法？

cc @SangKa, @tsiq-swyx

---

Due to some issues in translation with the upcoming awesome mobx bot, I've hit a bit of a stump. Do Chinese readers find much value in having these translations? I'm concerned that maintaining them is no longer worth the effort, since maintaining this list could be virtually free if we discarded them and instead allowed readers to translate as needed using something like Google Translate.

This would mean that discarding them (or rather, archiving them in another repo) would make management of this list much easier and allow information to be more easily kept up-to-date. 

What do our readers think about this?

**Comment by tsiq-swyx** [comment]
i merely speak chinese, but im native in English. I'm not the target
audience here.

**Comment by hawkins** [comment]
Of course; but that's valuable input still. Thanks! We may just not have enough Chinese-only users to keep maintaining this then.

**Comment by SangKa** [comment]
For the docs, the translations means a lot, but for the awesome list, it's better if have the translations, if don't, that's cool.
