### ISSUE TITLE
Potential real-world application 

### ISSUE THREAD

**Issue by nahueld** [mobxjs/awesome-mobx#62]
I've recently worked on the following project for an interview: [Portfolia](https://github.com/nahueld/portfolia)

Will this be useful as a 'real-world' application?

**Comment by hawkins** [comment]
Hey, thanks for pointing this out. Good work on it too, I like it! Feel free to open a PR with this added if you'd like to see it in 🙂

**Comment by hawkins** [comment]
Closed from #63
