### ISSUE TITLE
Please add mobx-binder to the list of relater projects

### ISSUE THREAD

**Issue by robaca** [mobxjs/awesome-mobx#76]
mobx-binder is a library for handling form state for React+MobX

thx

**Comment by robaca** [comment]
https://github.com/metro-nom/mobx-binder

**Comment by mweststrate** [comment]
Please open an PR instead😊

Op ma 23 sep. 2019 13:15 schreef Carsten Rohrbach <notifications@github.com

**Comment by robaca** [comment]
created PR #77
