### ISSUE TITLE
Re-sync who-uses MobX list

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/awesome-mobx#8]
See: https://github.com/mobxjs/mobx/issues/681

**Comment by hawkins** [comment]
Looks like [this](https://github.com/mobxjs/mobx/issues/681#issuecomment-265834883) is the next one to be added.

But, I'm not entirely sure that such a large table should be on the readme. What would you think about moving this to another file, such as `USERS.md` or similar? Maybe pick out some of the more widely-known company logos and keep their logos only in the bottom of the README but the full info of all companies in the other file?

**Comment by mweststrate** [comment]
Yeah that is a good idea, maybe just show the logo's of the top ~5 indeed
and a "...and many more" link.

>
