### ISSUE TITLE
Incorrect link in README

### ISSUE THREAD

**Issue by deadcoder0904** [mobxjs/awesome-mobx#89]
https://nealbuerger.com/2018/11/getting-started-with-mobx5-react16-and-typescript3.html should be https://www.nealbuerger.com/tech/typescript/2018-11-11-getting-started-with-mobx5-react16-and-typescript3/

**Comment by mweststrate** [comment]
Open a PR instead?

Op do 24 dec. 2020 07:34 schreef Akshay Kadam (A2K) <
notifications@github.com>:

**Comment by deadcoder0904** [comment]
Done
