### ISSUE TITLE
Add staff picks and popular picks badges

### ISSUE THREAD

**Issue by hawkins** [mobxjs/awesome-mobx#9]
Staff pick for links the MobX team wants to recognize:

| Single | Two-tone |
|:-:|:-:|
| ![alternative staff pick](https://img.shields.io/badge/-MobX%20Staff%20Pick-orange.svg) | ![staff pick](https://img.shields.io/badge/MobX-Staff%20Pick-orange.svg) |

Popular links for ones particularly popular in the wild:

| Single | Two-tone |
|:-:|:-:|
| ![alternative popular](https://img.shields.io/badge/-Popular%20in%20the%20Community-red.svg) | ![popular](https://img.shields.io/badge/MobX-Popular-red.svg) |

Anyone care to share the preferences between the two styles? I think I personally prefer the "Single" style

**Comment by mweststrate** [comment]
Yep single looks fine! I'll try to make a list of personal picks later today

**Comment by hawkins** [comment]
Staff picks merged, popular badges still to come

**Comment by hawkins** [comment]
The more I think about it, the less valuable popular badges are. I wouldn't know how to implement them aside from using middleman link shortening serviced and scraping statistics every so often, and that honestly might deter users because of the obvious vulnerabilities associated with link shorteners. Even I avoid clicking links I can't read.

So, I'm closing this since we have staff picks (and a lot of them!) to already guide users toward a few blessed resources.

**Comment by mweststrate** [comment]
:+1:

Op di 25 jul. 2017 om 14:27 schreef Josh Hawkins <notifications@github.com>:
